// SPDX-License-Identifier: GPL-3.0-or-later
using System;
using System.Reflection;
using HarmonyLib;

namespace StraftatCap
{
    /// <summary>
    /// Widens the max-players dropdown wherever vanilla builds or uses it.
    /// </summary>
    /// <remarks>
    /// Vanilla authors three options in the scene (2, 3, 4) and derives the cap
    /// straight from the selected index. Adding options is therefore the whole
    /// of the UI side of raising the cap - no vanilla code needs replacing.
    /// </remarks>
    [HarmonyPatch]
    internal static class SteamLobbyStartPatch
    {
        private static MethodBase TargetMethod() =>
            AccessTools.Method(AccessTools.TypeByName("SteamLobby"), "Start");

        private static void Postfix()
        {
            try
            {
                if (!Plugin.Active || !GameBridge.Usable) return;

                int max = Plugin.MaxPlayers;
                int expanded = GameBridge.ExpandAllMaxPlayersDropdowns(max);
                if (expanded == 0) Log.Warn("no max-players dropdown found to expand.");

                TransportCap.EnsureSubscribed();
            }
            catch (Exception e)
            {
                Log.Error($"SteamLobby.Start postfix failed: {e}");
            }
        }
    }

    /// <summary>
    /// Re-applies the transport cap when the host changes the lobby size.
    /// </summary>
    /// <remarks>
    /// Vanilla's own SetMaxPlayers already sets the transport, and for a lobby
    /// whose server is running that call does stick. This postfix exists because
    /// vanilla computes it from the dropdown while we want it computed from the
    /// clamped cap, and because it keeps one code path responsible for the value.
    /// </remarks>
    [HarmonyPatch]
    internal static class SetMaxPlayersPatch
    {
        private static MethodBase TargetMethod() =>
            AccessTools.Method(AccessTools.TypeByName("SteamLobby"), "SetMaxPlayers");

        private static void Postfix()
        {
            try
            {
                if (!Plugin.Active || !GameBridge.Usable) return;
                TransportCap.Apply("lobby size changed");
            }
            catch (Exception e)
            {
                Log.Error($"SetMaxPlayers postfix failed: {e}");
            }
        }
    }

    /// <summary>
    /// Makes sure the dropdown is wide before the host picks a size for a new
    /// lobby, and re-applies the cap once the lobby exists.
    /// </summary>
    [HarmonyPatch]
    internal static class OnLobbyCreatedPatch
    {
        private static MethodBase TargetMethod() =>
            AccessTools.Method(AccessTools.TypeByName("SteamLobby"), "OnLobbyCreated");

        private static void Prefix()
        {
            try
            {
                if (!Plugin.Active || !GameBridge.Usable) return;

                // Both dropdowns again: the in-lobby one is only built once the
                // lobby window exists, so Start alone may have missed it.
                GameBridge.ExpandAllMaxPlayersDropdowns(Plugin.MaxPlayers);
            }
            catch (Exception e)
            {
                Log.Error($"OnLobbyCreated prefix failed: {e}");
            }
        }

        private static void Postfix()
        {
            try
            {
                if (!Plugin.Active || !GameBridge.Usable) return;
                TransportCap.EnsureSubscribed();
                TransportCap.Apply("lobby created");
            }
            catch (Exception e)
            {
                Log.Error($"OnLobbyCreated postfix failed: {e}");
            }
        }
    }

    /// <summary>
    /// Keeps the cap that reaches clients inside the range this mod supports.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This matters more than it looks. Vanilla's Update kicks any player whose
    /// index is at or beyond their own copy of <c>maxPlayers</c>:
    /// </para>
    /// <code>
    /// for (int i = maxPlayers; i &lt; l; i++) { if (... == players[i] ...) KickSelf(); }
    /// </code>
    /// <para>
    /// That check runs on each client against its own value, so a client left
    /// holding a stale or nonsensical cap ejects itself from a lobby the host
    /// considers perfectly fine. Clamping what arrives keeps a malformed value
    /// from turning into a self-kick.
    /// </para>
    /// </remarks>
    [HarmonyPatch]
    internal static class UpdateOnClientsPatch
    {
        // Resolved once. Harmony calls both Prepare and TargetMethod, so an
        // uncached lookup scans the type repeatedly and logs the same line each
        // time - which is exactly what the first in-game run showed.
        private static MethodBase _resolved;
        private static bool _searched;

        private static MethodBase FindCapRpc()
        {
            if (_searched) return _resolved;
            _searched = true;

            // The RPC body is generated by FishNet's IL weaver, so its name
            // carries a hash suffix and exists in nobody's source. Find it by
            // prefix rather than hardcoding a number that a FishNet or signature
            // change would invalidate.
            var clientInstance = AccessTools.TypeByName("ClientInstance");
            if (clientInstance == null) return null;

            foreach (var method in AccessTools.GetDeclaredMethods(clientInstance))
            {
                if (!method.Name.StartsWith("RpcLogic___UpdateOnClients", StringComparison.Ordinal)) continue;

                var parameters = method.GetParameters();
                if (parameters.Length == 1 && parameters[0].ParameterType == typeof(int))
                {
                    Log.Info($"found cap RPC: {method.Name}");
                    _resolved = method;
                    return _resolved;
                }
            }

            Log.Warn("cap RPC (RpcLogic___UpdateOnClients*) not found; "
                     + "clients will use whatever value the host sends, unclamped.");
            return null;
        }

        private static MethodBase TargetMethod() => FindCapRpc();

        // Harmony skips a patch whose TargetMethod returns null only if we say
        // so explicitly; Prepare is the supported way to opt out.
        private static bool Prepare(MethodBase original) => FindCapRpc() != null;

        private static void Prefix(ref int maxPlayers)
        {
            try
            {
                if (!Plugin.Active) return;

                int clamped = CapMath.Clamp(maxPlayers);
                if (clamped != maxPlayers)
                {
                    Log.Warn($"cap of {maxPlayers} arrived from the host; clamping to {clamped}.");
                    maxPlayers = clamped;
                }
            }
            catch (Exception e)
            {
                Log.Error($"clamping the incoming cap failed: {e}");
            }
        }
    }
}
